### ISSUE TITLE
请问一下missing rate 是1.0的时候是什么情况？为什么还会有Acc？

### ISSUE THREAD

**Issue by Angus-GPZ** [Columbine21/TFR-Net#4]

**Comment by Columbine21** [comment]
missing rate 是 1.0 的时候（对应样本完全缺失，所有模态特征为全零序列），这种情况下模型的输出（理论上Acc-2应该接近于50%），计算Acc等指标只是为了统计意义上的结果（AUILC值计算的时候也可以忽略1.0的结果）。

**Comment by Angus-GPZ** [comment]
好的，非常感谢
